// This file is automatically generated. Do not modify it manually.

import manifest from '../../plugin.json';

export default manifest;
export const id = manifest.id;
export const version = manifest.version;
