// This file is automatically generated. Do not modify it manually.

package main

import "github.com/mattermost/mattermost-server/v5/model"

var manifest = model.Manifest{
	Id:      "com.mattermost.msteamsmeetings",
	Version: "1.0.1",
}
