// This file is automatically generated. Do not modify it manually.

package main

import "github.com/mattermost/mattermost-server/v6/model"

var manifest = model.Manifest{
	Id:      "com.mattermost.msteamsmeetings",
	Version: "2.0.0",
}
