// This file is automatically generated. Do not modify it manually.

package main

var manifest = struct {
	Id      string
	Version string
}{
	Id:      "com.mattermost.msteamsmeetings",
	Version: "1.0.0",
}
